name: Build

on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.rs"
      - "**.toml"
      - "**.lock"
      - ".github/workflows/*.yml"

env:
 CI_TOOLCHAIN: "1.76.0-x86_64-unknown-linux-gnu"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install ffi toolchain (1.76.0)
        run: |
          rustup install $CI_TOOLCHAIN
          rustup target add x86_64-apple-darwin --toolchain $CI_TOOLCHAIN
          rustup default $CI_TOOLCHAIN
      - name: Build Linux
        run: |
          cargo build
      - uses: actions/upload-artifact@v4
        with:
          path: "target/debug/libdrift_ffi_sys.so"
          name: libdrift_ffi_sys.so
      - name: Build Mac
        run: |
          cargo build --target x86_64-apple-darwin
      - uses: actions/upload-artifact@v4
        with:
          path: "target/x86_64-apple-darwin/debug/libdrift_ffi_sys.dylib"
          name: libdrift_ffi_sys.dylib
