name: Bump program version
on:
  repository_dispatch:
    types: ['sdk-update']

jobs:
  on-program-update:
    runs-on: ubicloud
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check update version
      run: |
        VERSION=$(curl -s "https://api.github.com/repos/drift-labs/protocol-v2/tags" | grep -m 1 "name" | cut -d '"' -f 4)
        echo "idl_version=$VERSION" >> $GITHUB_OUTPUT

        # Check if version contains beta, alpha, or rc tags
        if echo "$VERSION" | grep -qE "beta|alpha|rc"; then
          echo "SKIP_PR=true" >> $GITHUB_ENV
          echo "Skipping PR creation for pre-release version: $VERSION"
        else
          echo "SKIP_PR=false" >> $GITHUB_ENV
        fi

    - name: Update Cargo.toml
      if: env.SKIP_PR == 'false'
      run: |
        if ! sed -i 's/^version = ".*"/version = "'$IDL_VERSION'"/g' Cargo.toml; then
          echo "Failed to update version in Cargo.toml"
          exit 1
        fi

        if ! sed -i 's/^tag = ".*"/tag = "v'$IDL_VERSION'"/g' Cargo.toml; then
          echo "Failed to update tag in Cargo.toml"
          exit 1
        fi

        if ! grep "^version = \"$IDL_VERSION\"" Cargo.toml > /dev/null; then
          echo "Version update verification failed"
          exit 1
        fi

        echo "Successfully updated version in Cargo.toml to $IDL_VERSION:"
        grep "^version = " Cargo.toml

    - name: Cargo check
      if: env.SKIP_PR == 'false'
      run: |
        rustup install 1.76.0-x86_64-unknown-linux-gnu
        rustup default 1.76.0-x86_64-unknown-linux-gnu
        cargo -V
        cargo check

    - name: Create release commit+tag
      if: env.SKIP_PR == 'false'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Configure git
        git config user.name "GitHub Actions"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        # Make commit
        git add -u
        git commit -m "chore: bump program to $IDL_VERSION 🤖" --allow-empty
        git tag "$IDL_VERSION"

        git push origin master --tags -f
        git push origin master -f
