name: "[tmp] trigger dispatch"
on:
  push:
    branches:
      - tmp-dispatch

jobs:
  trigger-dispatch:
    runs-on: ubicloud
    steps:
    - name: trigger dispatch event
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: token ${{ secrets.GH_PAT }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/drift-labs/drift-ffi-sys/dispatches \
        -d '{"event_type":"sdk-update","client_payload":{"version":"2.111.0"}}'
